services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: foodeval-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - foodeval_mssql:/var/opt/mssql

volumes:
  foodeval_mssql:
